export const COUNTRIES = [
  'Argentina','Australia','Austria','Belgium','Bolivia','Brazil','Canada','Chile',
  'China','Colombia','Costa Rica','Cuba','Denmark','Dominican Republic','Ecuador',
  'Egypt','El Salvador','Finland','France','Germany','Greece','Guatemala','Honduras',
  'India','Indonesia','Ireland','Israel','Italy','Jamaica','Japan','Kenya',
  'Mexico','Morocco','Netherlands','New Zealand','Nicaragua','Nigeria','Norway',
  'Pakistan','Panama','Paraguay','Peru','Philippines','Poland','Portugal',
  'Romania','Russia','Saudi Arabia','South Africa','Spain','Sweden','Switzerland',
  'Turkey','Ukraine','United Kingdom','United States','Uruguay','Venezuela','Vietnam',
];

export const SLIDES = [
  { src: '/images/hero/hero1.avif', alt: 'Vista del hotel' },
  { src: '/images/hero/hero2.jpg',  alt: 'Habitación deluxe' },
  { src: '/images/hero/hero3.webp', alt: 'Piscina y jardines' },
  { src: '/images/hero/hero4.jpg',  alt: 'Restaurante' },
];

export const ROOM_IMAGES = [
  '/images/habitaciones/habitacion1.jpeg',
  '/images/habitaciones/habitacion2.webp',
  '/images/habitaciones/habitacion3.webp',
  '/images/habitaciones/habitacion4.jpg',
  '/images/habitaciones/habitacion5.jpg',
  '/images/habitaciones/habitacion6.webp',
  '/images/habitaciones/habitacion7.webp',
  '/images/habitaciones/habitacion8.jpg',
  '/images/habitaciones/habitacion9.jpg',
];

export const CURRENCIES = [
  { code: 'PEN', symbol: 'S/', name: 'Soles' },
  { code: 'USD', symbol: '$',  name: 'Dólar' },
  { code: 'EUR', symbol: '€',  name: 'Euro' },
  { code: 'BRL', symbol: 'R$', name: 'Real' },
  { code: 'COP', symbol: '$',  name: 'Peso COP' },
  { code: 'ARS', symbol: '$',  name: 'Peso ARS' },
];

export const T = {
  es: {
    badge: 'Reserva directa · Sin comisiones',
    heroTitle: 'Encuentra tu habitación perfecta',
    heroSub: 'Consulta disponibilidad en tiempo real y reserva en minutos',
    checkin: 'Check-in',
    checkout: 'Check-out',
    search: 'Buscar',
    searching: 'Buscando...',
    feat1Title: 'Disponibilidad en tiempo real',
    feat1Desc: 'Ve exactamente qué habitaciones están disponibles para tus fechas',
    feat2Title: 'Reserva segura',
    feat2Desc: 'Tu reserva queda confirmada inmediatamente en nuestro sistema',
    feat3Title: 'Sin intermediarios',
    feat3Desc: 'Reserva directo con el hotel, sin comisiones ni sobrecargos',
    availableRooms: (n: number) => `${n} habitación${n !== 1 ? 'es' : ''} disponible${n !== 1 ? 's' : ''}`,
    priceRealtime: (name: string) => `Precios en ${name} · tasa en tiempo real`,
    noRooms: 'No hay habitaciones disponibles',
    noRoomsSub: 'Intenta con otras fechas',
    changeDates: 'Cambiar fechas',
    perNight: 'por noche',
    total: 'Total',
    select: 'Seleccionar',
    people: 'personas',
    floor: 'Piso',
    bookingSummary: 'Resumen de la reserva',
    night: 'noche',
    nights: 'noches',
    change: 'Cambiar',
    continue: 'Continuar',
    selectRoom: 'Selecciona una habitación',
    guestData: 'Datos del huésped',
    guestDataSub: 'Completa tus datos para confirmar la reserva',
    firstName: 'Nombre',
    lastName: 'Apellido',
    nationality: 'Nacionalidad',
    selectCountry: 'Selecciona tu país',
    email: 'Correo electrónico',
    phone: 'Teléfono',
    dni: 'DNI / Pasaporte',
    notes: 'Notas adicionales',
    notesPlaceholder: 'Llegada tardía, peticiones especiales...',
    confirmBooking: 'Confirmar reserva',
    confirming: 'Confirmando reserva...',
    secure: 'Tus datos están protegidos y seguros',
    confirmed: '¡Reserva confirmada!',
    confirmedSub: (_email: string) => `Hemos enviado los detalles a`,
    reservationNum: 'Número de reserva',
    guest: 'Huésped',
    room: 'Habitación',
    newBooking: 'Hacer otra reserva',
    validDates: 'Selecciona fechas válidas.',
    fillRequired: 'Por favor completa todos los campos obligatorios.',
    errorSearch: 'Error al buscar habitaciones.',
    errorBooking: 'Error al crear la reserva.',
    rateRealtime: 'Tasa en tiempo real',
    hab: 'Hab.',
    footer: 'Todos los derechos reservados',
    footerSub: 'Reservas directas sin comisiones',
  },
  en: {
    badge: 'Direct booking · No commissions',
    heroTitle: 'Find your perfect room',
    heroSub: 'Check availability in real time and book in minutes',
    checkin: 'Check-in',
    checkout: 'Check-out',
    search: 'Search',
    searching: 'Searching...',
    feat1Title: 'Real-time availability',
    feat1Desc: 'See exactly which rooms are available for your dates',
    feat2Title: 'Secure booking',
    feat2Desc: 'Your reservation is confirmed immediately in our system',
    feat3Title: 'No middlemen',
    feat3Desc: 'Book directly with the hotel, no commissions or surcharges',
    availableRooms: (n: number) => `${n} room${n !== 1 ? 's' : ''} available`,
    priceRealtime: (name: string) => `Prices in ${name} · real-time rate`,
    noRooms: 'No rooms available',
    noRoomsSub: 'Try different dates',
    changeDates: 'Change dates',
    perNight: 'per night',
    total: 'Total',
    select: 'Select',
    people: 'guests',
    floor: 'Floor',
    bookingSummary: 'Booking summary',
    night: 'night',
    nights: 'nights',
    change: 'Change',
    continue: 'Continue',
    selectRoom: 'Select a room',
    guestData: 'Guest details',
    guestDataSub: 'Complete your details to confirm the booking',
    firstName: 'First name',
    lastName: 'Last name',
    nationality: 'Nationality',
    selectCountry: 'Select your country',
    email: 'Email address',
    phone: 'Phone',
    dni: 'ID / Passport',
    notes: 'Additional notes',
    notesPlaceholder: 'Late arrival, special requests...',
    confirmBooking: 'Confirm booking',
    confirming: 'Confirming booking...',
    secure: 'Your data is protected and secure',
    confirmed: 'Booking confirmed!',
    confirmedSub: (_email: string) => `We sent the details to`,
    reservationNum: 'Reservation number',
    guest: 'Guest',
    room: 'Room',
    newBooking: 'Make another booking',
    validDates: 'Please select valid dates.',
    fillRequired: 'Please fill in all required fields.',
    errorSearch: 'Error searching for rooms.',
    errorBooking: 'Error creating the booking.',
    rateRealtime: 'Real-time rate',
    hab: 'Rm.',
    footer: 'All rights reserved',
    footerSub: 'Direct bookings, no commissions',
  },
};

export type Lang = 'es' | 'en';
export type TDict = typeof T.es;